apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-deployment
spec:
  selector:
    matchLabels:
      app: datastore
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
      - name: datastore
        image: localhost:5252/mysql-volume:latest
        ports:
        - containerPort: 3306	

---
apiVersion: v1
kind: Service
metadata:
  name: datastore-service
spec:
  type: NodePort
  selector:
    app: datastore
  ports:
    - protocol: TCP
      name: mysql-port
      port: 3306
      targetPort: 3306
      nodePort: 30003

